{"name": "test_create_order_invalid_ingredients", "status": "broken", "statusDetails": {"message": "NameError: name 'AUTH_TOKEN' is not defined", "trace": "def test_create_order_invalid_ingredients():\n        url = f\"{BASE_URL}/orders\"\n>       headers = {\"Authorization\": f\"Bearer {AUTH_TOKEN}\"}\nE       NameError: name 'AUTH_TOKEN' is not defined\n\napi_tests/test_order_creation.py:27: NameError"}, "start": 1725805832078, "stop": 1725805832078, "uuid": "dce58418-85a8-4a02-abde-c8e39d50c10a", "historyId": "cd50c16bab948bf599c6121ba992fafc", "testCaseId": "cd50c16bab948bf599c6121ba992fafc", "fullName": "api_tests.test_order_creation#test_create_order_invalid_ingredients", "labels": [{"name": "parentSuite", "value": "api_tests"}, {"name": "suite", "value": "test_order_creation"}, {"name": "host", "value": "MacBook-Air-Anna.local"}, {"name": "thread", "value": "94963-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "api_tests.test_order_creation"}]}